- Effect: "Allow"
  Action:
    - "mediaconvert:DescribeEndpoints"
    - "mediaconvert:CreateJob"
  Resource: "*"
- Effect: "Allow"
  Action:
    - iam:PassRole
  Resource: arn:aws:iam::#{AWS::AccountId}:role/${self:service}Role${self:custom.stage.suffix}
